### ISSUE TITLE
Unable to import kubeadm_generate due to invalid syntax

### ISSUE THREAD

**Issue by andrii-82** [raspbernetes/k8s-cluster-installation#60]
Hi!
Grate project! Thanks for your work!

I'm new in ansible and kubernetes. So far I'm trying to setup HA cluster of three RPi's and I faced with problem - ansible fails on token generation:
```
TASK [cluster : generate kubeadm token] *****************************************************************************************************************************************************
Monday 24 August 2020  23:04:56 +0300 (0:00:01.579)       0:04:50.679 *********
fatal: [k8s-node-101]: FAILED! =>
  msg: Unable to import kubeadm_generate due to invalid syntax
```
My setup:
```
Ansible node:
- OS: Raspbian GNU/Linux 10 (buster)
- Python 2.7.16
Cluster:
- three Raspberry Pi 4 Model B, all master nodes which should also take workloads (act as workers as well)
- OS - Ubuntu 20.04.1 LTS
- kubeadm, kubectl, kubelet - 1.18.8-00
- docker - 19.03.12~3-0~ubuntu-focal
```
Please advise how to find out where is the problem! What file contains "invalid syntax".
Thank you in advance!

**Comment by xunholy** [comment]
@andrii-82 Welcome, and thanks for raising this issue. Could you please share the contents of your inventory file. 

I'm currently also running RPIs with 3 masters, 1 worker setup. I would recommend following this guide https://itnext.io/automated-ha-kubernetes-deployment-on-raspberry-pis-408f38cd836c which is intended to give really good instructions on using this repo and how to configure certain aspects.

@RobReus will also be able to have a look into the python script to see what might have caused this type of error.

**Comment by andrii-82** [comment]
Here is the content of my inventory file:
```
[masters]
k8s-node-101 hostname=k8s-node-101 ansible_host=192.168.50.101 ansible_user=pi
k8s-node-102 hostname=k8s-node-102 ansible_host=192.168.50.102 ansible_user=pi
k8s-node-103 hostname=k8s-node-103 ansible_host=192.168.50.103 ansible_user=pi
```
BR

**Comment by andrii-82** [comment]
Hi @xUnholy!

I was able to setup HA cluster. That "syntax" error which I posted previously was related to python version (I believe) cause when I removed python 2.7 and reinstalled ansible with python3, that error went away.
But there was another problem which I was able to manage - during "cluster join" process secondary nodes were not able to join because of some networking problem which can not understand. Those nodes were not able to ping VIP of load balancer with error "no route to host" despite ALL nodes and VIP LB are in the same subnet and in the same broadcast domain.
So, I configured static routes to the VIP on all nodes and after that HA cluster came alive!!!!  

Thanks all of you for your work under this project!

**Comment by xunholy** [comment]
Thanks for the feedback and we'll see how we can improve that experience in the future to ensure its easy for future use.

**Comment by RobReus** [comment]
It is correct that python2 can/will give issues as nothing is tested against python2, it being End of Life and all. You upgrading to python3 was indeed the correct course of action. We'll see if we can perhaps clearly document this, or put a fail message whenever someone tries to run it using python2.

Regarding the no route to host issue, that is a LAN issue on your end. If the VIP used is within the same subnet as your normal IPs, it should work via ARP. Do keep in mind that the VIP is only assigned to one specific node at a time via keepalived, and only that node will respond to ARP requests. Its weird that configuring a static route to the VIP works, as its within the same subnet as your regular IPs, meaning there should already be a route for that whole subnet.

Its pretty hard to troubleshoot something like this via a github issue. Feel free to hop on discord so we can help you troubleshoot the network issues to get everything working normally. You can join via https://discord.gg/RGvKzVg if not done so already.
