### ISSUE TITLE
Containerd assumes arm64 for apt repo location

### ISSUE THREAD

**Issue by carpenike** [raspbernetes/k8s-cluster-installation#64]
See here: https://github.com/raspbernetes/k8s-cluster-installation/blob/master/ansible/roles/cri/tasks/containerd.yml#L30

**Comment by RobReus** [comment]
@xUnholy I see no harm in removing the `[arch=arm64]` part for the apt repo of docker, do you? By removing the arm64 arch specific option, all arch types which are supported by the apt repo can be used.

**Comment by xunholy** [comment]
Yep we should be able to remove the arch from this and look to see if there are any other similar places we can address.
