### ISSUE TITLE
RFC: Uninstall snap and Ubuntu telemetry packages

### ISSUE THREAD

**Issue by onedr0p** [raspbernetes/k8s-cluster-installation#67]
I was reading an interesting article on snap and Ubuntu and it seems like the consensus is that it's 💩 

https://news.ycombinator.com/item?id=22972661

What do you guys think about uninstalling that and the Ubuntu telemetry packages? I can open a PR if you agree 🙂

    - apport
    - popularity-contest
    - snapd
    - sosreport
    - ubuntu-advantage-tools

Apport*: https://wiki.ubuntu.com/Apport - "Apport collects potentially sensitive data, such as core dumps, stack traces, and log files. They can contain passwords, credit card numbers, serial numbers, and other private material."

sosreport: "generates a compressed tarball of debugging information for the system it is run on that can be sent to technical support reps that will give them a more complete view of the overall system status." This is sent to canonical.

popularity-contest: "The popularity-contest package sets up a cron job that will periodically anonymously submit to the Ubuntu developers statistics about the most used Ubuntu packages on this system." This is sent to canonical.

ubuntu-advantage-tools: This is a paid service offered by Ubuntu https://ubuntu.com/legal/ubuntu-advantage

**Comment by crutonjohn** [comment]
While I mostly agree with your assertion of Snap and the like being terrible, I think taking an opinionated stance from the perspective of this particular repo is not necessarily "in-scope". Due to the wonderful nature of Ansible, it would be fairly trivial to use `ansible-galaxy` to include a remote role to remove said packages.
