### ISSUE TITLE
Task kubernetes : enable required cgroup features skips if user added cmdline options are present

### ISSUE THREAD

**Issue by anthr76** [raspbernetes/k8s-cluster-installation#73]
# Details

**What steps did you take and what happened:**

Run the ansible-playbook and encounter a failure when looking for the sha256 of the Kubernetes certificate. This is never created because cgroups are never set on debian based distros.

> Note: This should be a clear and concise description of what the bug is.

**What did you expect to happen:**
`cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory` to be added to `/boot/cmdline.txt`

**Anything else you would like to add:**

https://github.com/raspbernetes/k8s-cluster-installation/blob/28b3d691b96b4a2df42199f8599b87e887a88d97/ansible/roles/kubernetes/tasks/debian.yml#L92 Line in question is this. This is caused when user added options are added. Logic to work around this is required. Currently I have `usb-storage.quirks` after `fixrtc` which is required for me to boot my OS off a External USB SSD

**Comment by xunholy** [comment]
### Solution

For anyone who experiences a similar issue try add the `usb-storage.quirks` option to the start of the cmdline.txt
