### ISSUE TITLE
fatal: [k8s-master-01]: FAILED! => changed=false

### ISSUE THREAD

**Issue by rmiddle** [raspbernetes/k8s-cluster-installation#83]
TASK [keepalived : validate variable : keepalived_vip] **************************************************************************************************************************************************
Tuesday 29 December 2020  00:21:44 -0500 (0:00:00.219)       0:02:54.059 ******
fatal: [k8s-master-01]: FAILED! => changed=false
  assertion: keepalived_vip | ipaddr
  evaluated_to: false
  msg:
  - Variable 'keepalived_vip' should be a valid ip address
  - 'Type is: AnsibleUnicode'
  - 'Value is: '
fatal: [k8s-master-02]: FAILED! => changed=false
  assertion: keepalived_vip | ipaddr
  evaluated_to: false
  msg:
  - Variable 'keepalived_vip' should be a valid ip address
  - 'Type is: AnsibleUnicode'
  - 'Value is: '
fatal: [k8s-master-03]: FAILED! => changed=false
  assertion: keepalived_vip | ipaddr
  evaluated_to: false
  msg:
  - Variable 'keepalived_vip' should be a valid ip address
  - 'Type is: AnsibleUnicode'
  - 'Value is: '

**Comment by rmiddle** [comment]
Found the issue.  I needed to define an VIP address in one of the config files.  It was in the example folder likely need to have the documentation updated to include the IP requirement

**Comment by xunholy** [comment]
This was an additional configuration item that was only highlighted in the recent blog post https://raspbernetes.github.io/blog/16-7-20 however, missed in the main documentation. I'll make sure we update the existing documentation, much appreciate @rmiddle !

**Comment by xunholy** [comment]
Thanks again for the feedback, I've just updated the docs, if there are any other improvements feel free to raise another issue or pull request - https://github.com/raspbernetes/docs/commit/ccc8cab9053faf25f1bc5e82f9a29629cf2524bf
